version: "3.9"

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - /client/node_modules
    # depends_on:
    #   - db
  server:
    build: ./server
    ports:
      - "5005:5005"
    volumes:
      - ./server:/server
      - /server/node_modules
